describe('Step 2', () => {
  const host = Cypress.env('host')
  it('It should load the 4 node sizes', () => {
    cy.visit(`${host}/#/protocol`)
    cy.get('#nodeSize option').should('have.length', 4)
  })
  it('It should display a recommendation if ServerType=Validator & Size=small', () => {
    cy.visit(`${host}`)
    cy.get('#serverType').select('validatorServer')
    cy.visit(`${host}/#/protocol`)
    cy.get('#nodeSize').select('small')
    cy.get('#recommendations_rec0003').should('exist')
  })
  it('It should display a recommendation if ServerType=Validator & Size=tiny', () => {
    cy.visit(`${host}`)
    cy.get('#serverType').select('validatorServer')
    cy.visit(`${host}/#/protocol`)
    cy.get('#nodeSize').select('tiny')
    cy.get('#recommendations_rec0003').should('exist')
  })
  it('It should display a recommendation if ServerType=Validator & Size=medium', () => {
    cy.visit(`${host}`)
    cy.get('#serverType').select('validatorServer')
    cy.visit(`${host}/#/protocol`)
    cy.get('#nodeSize').select('medium')
    cy.get('#recommendations_rec0003').should('exist')
  })
  it('It should not display a recommendation if ServerType!=Validator & Size!=huge', () => {
    cy.visit(`${host}`)
    cy.get('#serverType').select('apiServer')
    cy.visit(`${host}/#/protocol`)
    cy.get('#nodeSize').select('huge')
    cy.get('#recommendations_rec0003').should('not.exist')
  })
  it('It should not display a recommendation if ServerType=Validator & Size=huge', () => {
    cy.visit(`${host}`)
    cy.get('#serverType').select('validatorServer')
    cy.visit(`${host}/#/protocol`)
    cy.get('#nodeSize').select('huge')
    cy.get('#recommendations_rec0003').should('not.exist')
  })
  it('It should load the devnet site list if Network=DEV', () => {
    cy.visit(`${host}/#/protocol`)
    cy.get('#network').select('devnet')
    cy.get('#validatorSitesOptions option').should('have.length', 1)
  })
  it('It should load the devnet site list if Network=TEST', () => {
    cy.visit(`${host}/#/protocol`)
    cy.get('#network').select('testnet')
    cy.get('#validatorSitesOptions option').should('have.length', 1)
  })
  it('It should load the mainnet site list if Network=MAIN', () => {
    cy.visit(`${host}/#/protocol`)
    cy.get('#network').select('mainnet')
    cy.get('#validatorSitesOptions option').should('have.length', 3)
  })
})
